// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgxstore

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type OrderStatusType string

const (
	OrderStatusTypeNEW        OrderStatusType = "NEW"
	OrderStatusTypePROCESSING OrderStatusType = "PROCESSING"
	OrderStatusTypeINVALID    OrderStatusType = "INVALID"
	OrderStatusTypePROCESSED  OrderStatusType = "PROCESSED"
)

func (e *OrderStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatusType(s)
	case string:
		*e = OrderStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatusType: %T", src)
	}
	return nil
}

type NullOrderStatusType struct {
	OrderStatusType OrderStatusType `json:"order_status_type"`
	Valid           bool            `json:"valid"` // Valid is true if OrderStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatusType), nil
}

func (e OrderStatusType) Valid() bool {
	switch e {
	case OrderStatusTypeNEW,
		OrderStatusTypePROCESSING,
		OrderStatusTypeINVALID,
		OrderStatusTypePROCESSED:
		return true
	}
	return false
}

func AllOrderStatusTypeValues() []OrderStatusType {
	return []OrderStatusType{
		OrderStatusTypeNEW,
		OrderStatusTypePROCESSING,
		OrderStatusTypeINVALID,
		OrderStatusTypePROCESSED,
	}
}

type ProcessStatusType string

const (
	ProcessStatusTypeNEW             ProcessStatusType = "NEW"
	ProcessStatusTypeSTARTPROCESSING ProcessStatusType = "START_PROCESSING"
	ProcessStatusTypeREGISTERED      ProcessStatusType = "REGISTERED"
	ProcessStatusTypePROCESSED       ProcessStatusType = "PROCESSED"
)

func (e *ProcessStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProcessStatusType(s)
	case string:
		*e = ProcessStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProcessStatusType: %T", src)
	}
	return nil
}

type NullProcessStatusType struct {
	ProcessStatusType ProcessStatusType `json:"process_status_type"`
	Valid             bool              `json:"valid"` // Valid is true if ProcessStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProcessStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.ProcessStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProcessStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProcessStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProcessStatusType), nil
}

func (e ProcessStatusType) Valid() bool {
	switch e {
	case ProcessStatusTypeNEW,
		ProcessStatusTypeSTARTPROCESSING,
		ProcessStatusTypeREGISTERED,
		ProcessStatusTypePROCESSED:
		return true
	}
	return false
}

func AllProcessStatusTypeValues() []ProcessStatusType {
	return []ProcessStatusType{
		ProcessStatusTypeNEW,
		ProcessStatusTypeSTARTPROCESSING,
		ProcessStatusTypeREGISTERED,
		ProcessStatusTypePROCESSED,
	}
}

type TransactionType string

const (
	TransactionTypeDEPOSIT  TransactionType = "DEPOSIT"
	TransactionTypeWITHDRAW TransactionType = "WITHDRAW"
	TransactionTypeINIT     TransactionType = "INIT"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType `json:"transaction_type"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

func (e TransactionType) Valid() bool {
	switch e {
	case TransactionTypeDEPOSIT,
		TransactionTypeWITHDRAW,
		TransactionTypeINIT:
		return true
	}
	return false
}

func AllTransactionTypeValues() []TransactionType {
	return []TransactionType{
		TransactionTypeDEPOSIT,
		TransactionTypeWITHDRAW,
		TransactionTypeINIT,
	}
}

type Order struct {
	ID          uuid.UUID       `db:"id" json:"id"`
	UserID      uuid.UUID       `db:"user_id" json:"user_id"`
	OrderNumber string          `db:"order_number" json:"order_number"`
	Status      OrderStatusType `db:"status" json:"status"`
	Accrual     decimal.Decimal `db:"accrual" json:"accrual"`
	CreatedAt   time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt   *time.Time      `db:"updated_at" json:"updated_at"`
	DeletedAt   *time.Time      `db:"deleted_at" json:"deleted_at"`
}

type OrdersToProcess struct {
	OrderNumber   string            `db:"order_number" json:"order_number"`
	ProcessStatus ProcessStatusType `db:"process_status" json:"process_status"`
	CreatedAt     time.Time         `db:"created_at" json:"created_at"`
	UpdatedAt     *time.Time        `db:"updated_at" json:"updated_at"`
	DeletedAt     *time.Time        `db:"deleted_at" json:"deleted_at"`
}

type Transaction struct {
	ID          uuid.UUID       `db:"id" json:"id"`
	OrderNumber *string         `db:"order_number" json:"order_number"`
	UserID      uuid.UUID       `db:"user_id" json:"user_id"`
	OldBalance  decimal.Decimal `db:"old_balance" json:"old_balance"`
	Change      decimal.Decimal `db:"change" json:"change"`
	NewBalance  decimal.Decimal `db:"new_balance" json:"new_balance"`
	Type        TransactionType `db:"type" json:"type"`
	CreatedAt   *time.Time      `db:"created_at" json:"created_at"`
}

type User struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	Login        string     `db:"login" json:"login"`
	PasswordHash string     `db:"password_hash" json:"password_hash"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt    *time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt    *time.Time `db:"deleted_at" json:"deleted_at"`
}
