// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgxstore

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (*Order, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	GetAllUsers(ctx context.Context) ([]*User, error)
	GetOrderByNumber(ctx context.Context, orderNumber string) (*Order, error)
	GetUserById(ctx context.Context, id uuid.UUID) (*User, error)
	GetUserByLogin(ctx context.Context, login string) (*User, error)
	GetUserOrders(ctx context.Context, userID uuid.UUID) ([]*Order, error)
	PutOrderForProcessing(ctx context.Context, orderNumber string) (*OrdersToProcess, error)
}

var _ Querier = (*Queries)(nil)
