// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/Kopleman/gophermart/internal/common/dto"
	decimal "github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// BalanceRepo is an autogenerated mock type for the BalanceRepo type
type BalanceRepo struct {
	mock.Mock
}

// GetUserBalance provides a mock function with given fields: ctx, userID
func (_m *BalanceRepo) GetUserBalance(ctx context.Context, userID uuid.UUID) (decimal.Decimal, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBalance")
	}

	var r0 decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (decimal.Decimal, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) decimal.Decimal); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserWithdrawalsSum provides a mock function with given fields: ctx, userID
func (_m *BalanceRepo) GetUserWithdrawalsSum(ctx context.Context, userID uuid.UUID) (decimal.Decimal, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserWithdrawalsSum")
	}

	var r0 decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (decimal.Decimal, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) decimal.Decimal); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MakeWithdraw provides a mock function with given fields: ctx, _a1
func (_m *BalanceRepo) MakeWithdraw(ctx context.Context, _a1 *dto.WithdrawDTO) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for MakeWithdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.WithdrawDTO) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBalanceRepo creates a new instance of BalanceRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalanceRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *BalanceRepo {
	mock := &BalanceRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
