// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/Kopleman/gophermart/internal/common/dto"
	mock "github.com/stretchr/testify/mock"

	pgxstore "github.com/Kopleman/gophermart/internal/pgxstore"

	uuid "github.com/google/uuid"
)

// OrderRepo is an autogenerated mock type for the OrderRepo type
type OrderRepo struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, createDTO
func (_m *OrderRepo) CreateOrder(ctx context.Context, createDTO *dto.CreateOrderDTO) (*pgxstore.Order, *pgxstore.OrdersToProcess, error) {
	ret := _m.Called(ctx, createDTO)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *pgxstore.Order
	var r1 *pgxstore.OrdersToProcess
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateOrderDTO) (*pgxstore.Order, *pgxstore.OrdersToProcess, error)); ok {
		return rf(ctx, createDTO)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateOrderDTO) *pgxstore.Order); ok {
		r0 = rf(ctx, createDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgxstore.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateOrderDTO) *pgxstore.OrdersToProcess); ok {
		r1 = rf(ctx, createDTO)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*pgxstore.OrdersToProcess)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *dto.CreateOrderDTO) error); ok {
		r2 = rf(ctx, createDTO)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetOrderByNumber provides a mock function with given fields: ctx, orderNumber
func (_m *OrderRepo) GetOrderByNumber(ctx context.Context, orderNumber string) (*pgxstore.Order, error) {
	ret := _m.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByNumber")
	}

	var r0 *pgxstore.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*pgxstore.Order, error)); ok {
		return rf(ctx, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *pgxstore.Order); ok {
		r0 = rf(ctx, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgxstore.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserOrders provides a mock function with given fields: ctx, userID
func (_m *OrderRepo) GetUserOrders(ctx context.Context, userID uuid.UUID) ([]*pgxstore.Order, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserOrders")
	}

	var r0 []*pgxstore.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*pgxstore.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*pgxstore.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pgxstore.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderRepo creates a new instance of OrderRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepo {
	mock := &OrderRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
