// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/Kopleman/gophermart/internal/common/dto"
	mock "github.com/stretchr/testify/mock"

	pgxstore "github.com/Kopleman/gophermart/internal/pgxstore"

	uuid "github.com/google/uuid"
)

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

// CreateNewUser provides a mock function with given fields: ctx, createDto
func (_m *UserRepo) CreateNewUser(ctx context.Context, createDto *dto.CreateUserDTO) (*pgxstore.User, error) {
	ret := _m.Called(ctx, createDto)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewUser")
	}

	var r0 *pgxstore.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateUserDTO) (*pgxstore.User, error)); ok {
		return rf(ctx, createDto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateUserDTO) *pgxstore.User); ok {
		r0 = rf(ctx, createDto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgxstore.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateUserDTO) error); ok {
		r1 = rf(ctx, createDto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: ctx, login
func (_m *UserRepo) GetUser(ctx context.Context, login string) (*pgxstore.User, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *pgxstore.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*pgxstore.User, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *pgxstore.User); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgxstore.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserWithdrawals provides a mock function with given fields: ctx, userID
func (_m *UserRepo) GetUserWithdrawals(ctx context.Context, userID uuid.UUID) ([]*pgxstore.Transaction, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserWithdrawals")
	}

	var r0 []*pgxstore.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*pgxstore.Transaction, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*pgxstore.Transaction); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pgxstore.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
