// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// HTTPClient is an autogenerated mock type for the HTTPClient type
type HTTPClient struct {
	mock.Mock
}

// Get provides a mock function with given fields: url, contentType
func (_m *HTTPClient) Get(url string, contentType string) ([]byte, *http.Response, error) {
	ret := _m.Called(url, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) ([]byte, *http.Response, error)); ok {
		return rf(url, contentType)
	}
	if rf, ok := ret.Get(0).(func(string, string) []byte); ok {
		r0 = rf(url, contentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) *http.Response); ok {
		r1 = rf(url, contentType)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(url, contentType)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewHTTPClient creates a new instance of HTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPClient {
	mock := &HTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
