// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	pgxstore "github.com/Kopleman/gophermart/internal/pgxstore"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepoForAccrual is an autogenerated mock type for the OrderRepoForAccrual type
type OrderRepoForAccrual struct {
	mock.Mock
}

// GetRegisteredProcessingOrders provides a mock function with given fields: ctx, limit
func (_m *OrderRepoForAccrual) GetRegisteredProcessingOrders(ctx context.Context, limit int32) ([]*pgxstore.OrdersToProcess, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRegisteredProcessingOrders")
	}

	var r0 []*pgxstore.OrdersToProcess
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]*pgxstore.OrdersToProcess, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []*pgxstore.OrdersToProcess); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pgxstore.OrdersToProcess)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStartProcessingOrders provides a mock function with given fields: ctx
func (_m *OrderRepoForAccrual) GetStartProcessingOrders(ctx context.Context) ([]*pgxstore.OrdersToProcess, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStartProcessingOrders")
	}

	var r0 []*pgxstore.OrdersToProcess
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*pgxstore.OrdersToProcess, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*pgxstore.OrdersToProcess); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pgxstore.OrdersToProcess)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PickOrdersToProcess provides a mock function with given fields: ctx, limit
func (_m *OrderRepoForAccrual) PickOrdersToProcess(ctx context.Context, limit int32) ([]*pgxstore.OrdersToProcess, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for PickOrdersToProcess")
	}

	var r0 []*pgxstore.OrdersToProcess
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]*pgxstore.OrdersToProcess, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []*pgxstore.OrdersToProcess); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pgxstore.OrdersToProcess)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterOrderProcessing provides a mock function with given fields: ctx, orderNumber
func (_m *OrderRepoForAccrual) RegisterOrderProcessing(ctx context.Context, orderNumber string) error {
	ret := _m.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for RegisterOrderProcessing")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, orderNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StoreAccrualCalculation provides a mock function with given fields: ctx, params
func (_m *OrderRepoForAccrual) StoreAccrualCalculation(ctx context.Context, params pgxstore.AccrualCalculationParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for StoreAccrualCalculation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgxstore.AccrualCalculationParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderRepoForAccrual creates a new instance of OrderRepoForAccrual. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepoForAccrual(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepoForAccrual {
	mock := &OrderRepoForAccrual{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
