definitions:
  controller.LoginResponseDto:
    properties:
      token:
        example: some_token
        type: string
    type: object
  dto.CreateUserRequestDTO:
    properties:
      login:
        example: login
        type: string
      password:
        example: password
        type: string
    type: object
  dto.OrderInfoDTO:
    properties:
      accrual:
        example: 500
        type: number
      order_number:
        example: "49927398716"
        type: string
      status:
        example: NEW
        type: string
      uploaded_at:
        example: "2020-12-10T15:12:01+03:00"
        type: string
    type: object
  dto.UserLoginRequestDTO:
    properties:
      login:
        example: login
        type: string
      password:
        example: password
        type: string
    type: object
info:
  contact: {}
paths:
  /api/user/login:
    post:
      consumes:
      - application/json
      description: Performs user login, returns jwt token
      parameters:
      - description: Body params
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.LoginResponseDto'
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Performs user login
      tags:
      - auth
  /api/user/orders:
    get:
      consumes:
      - text/plain
      description: Fetch list of users orders
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.OrderInfoDTO'
            type: array
        "204":
          description: Accepted
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Fetch list of users orders
      tags:
      - order
    post:
      consumes:
      - text/plain
      description: Add new user order to system
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Body params
        in: body
        name: data
        required: true
        schema:
          type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "409":
          description: invalid order number
          schema:
            type: string
        "422":
          description: invalid order number
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Add new order
      tags:
      - order
  /api/user/register:
    post:
      consumes:
      - application/json
      description: Register new user
      parameters:
      - description: Body params
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequestDTO'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "409":
          description: User already exists
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Register new user
      tags:
      - auth
swagger: "2.0"
