// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/Kopleman/gophermart/internal/common/dto"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// BalanceService is an autogenerated mock type for the BalanceService type
type BalanceService struct {
	mock.Mock
}

// GetUserBalanceDTO provides a mock function with given fields: ctx, userID
func (_m *BalanceService) GetUserBalanceDTO(ctx context.Context, userID uuid.UUID) (*dto.BalanceDTO, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBalanceDTO")
	}

	var r0 *dto.BalanceDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.BalanceDTO, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.BalanceDTO); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.BalanceDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MakeWithdraw provides a mock function with given fields: ctx, requestDTO
func (_m *BalanceService) MakeWithdraw(ctx context.Context, requestDTO *dto.WithdrawDTO) error {
	ret := _m.Called(ctx, requestDTO)

	if len(ret) == 0 {
		panic("no return value specified for MakeWithdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.WithdrawDTO) error); ok {
		r0 = rf(ctx, requestDTO)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBalanceService creates a new instance of BalanceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalanceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BalanceService {
	mock := &BalanceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
