// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/Kopleman/gophermart/internal/common/dto"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, createDTO
func (_m *OrderService) CreateOrder(ctx context.Context, createDTO *dto.CreateOrderDTO) error {
	ret := _m.Called(ctx, createDTO)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateOrderDTO) error); ok {
		r0 = rf(ctx, createDTO)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrderByNumber provides a mock function with given fields: ctx, orderNumber
func (_m *OrderService) GetOrderByNumber(ctx context.Context, orderNumber string) (*dto.OrderDTO, error) {
	ret := _m.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByNumber")
	}

	var r0 *dto.OrderDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.OrderDTO, error)); ok {
		return rf(ctx, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.OrderDTO); ok {
		r0 = rf(ctx, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.OrderDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserOrders provides a mock function with given fields: ctx, userID
func (_m *OrderService) GetUserOrders(ctx context.Context, userID uuid.UUID) ([]*dto.OrderDTO, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserOrders")
	}

	var r0 []*dto.OrderDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*dto.OrderDTO, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*dto.OrderDTO); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.OrderDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
