// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/Kopleman/gophermart/internal/common/dto"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// AuthorizeUser provides a mock function with given fields: ctx, loginDto
func (_m *UserService) AuthorizeUser(ctx context.Context, loginDto *dto.UserCredentialsDTO) (string, error) {
	ret := _m.Called(ctx, loginDto)

	if len(ret) == 0 {
		panic("no return value specified for AuthorizeUser")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UserCredentialsDTO) (string, error)); ok {
		return rf(ctx, loginDto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UserCredentialsDTO) string); ok {
		r0 = rf(ctx, loginDto)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.UserCredentialsDTO) error); ok {
		r1 = rf(ctx, loginDto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, createDto
func (_m *UserService) CreateUser(ctx context.Context, createDto *dto.UserCredentialsDTO) error {
	ret := _m.Called(ctx, createDto)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UserCredentialsDTO) error); ok {
		r0 = rf(ctx, createDto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWithdrawals provides a mock function with given fields: ctx, userID
func (_m *UserService) GetWithdrawals(ctx context.Context, userID uuid.UUID) ([]*dto.WithdrawalItemDTO, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawals")
	}

	var r0 []*dto.WithdrawalItemDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*dto.WithdrawalItemDTO, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*dto.WithdrawalItemDTO); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.WithdrawalItemDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
